global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
    alertmanagers:
      - static_configs:
          - targets: []
        scheme: http
        timeout: 10s
        api_version: v1

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090
  - job_name: node_exporter_localmac
    static_configs:
      - targets: ['192.168.28.10:9100']

  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['node_exporter:9100']

  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # - job_name: 'grafana'
  #   static_configs:
  #     - targets: ['grafana:3000']

